LOAD DATA LOCAL INFILE 'student.csv' INTO TABLE student FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'instructor.csv' INTO TABLE instructor FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'class.csv' INTO TABLE class FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'studentClass.csv' INTO TABLE studentClass FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'question.csv' INTO TABLE question FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'classQuestions.csv' INTO TABLE classQuestions FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\r\n';
LOAD DATA LOCAL INFILE 'studentResponses.csv' INTO TABLE studentResponses FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\r\n';
